### PR TITLE
Spotbugs

### PR DESCRIPTION
**Pull request by alexrknowles**
SpotBugs has been successfully implemented into the build. Report generation succeeds with some internal SpotBug errors, but could just be related to the plug-in itself.

### CODE REVIEW

**Review by jody — CHANGES_REQUESTED** [review]
If this is addressing #115 why were there changes necessary to 4 files (several of which don't seem to have any changes directly related to SpotBugs integration)?

**Comment by jreiser1** [comment]
It seems like some work related to another feature I was working on might have made its way into this feature branch. I'll try and roll back my unrelated changes so that the build.gradle file is the only thing that is changed for this pull request

**Comment by jreiser1** [comment]
I was unable to cleanly roll back my unrelated changes, so I just created Pull Request #162, which should have only the necessary changes for the SpotBugs implementation. My apologies for any confusion this may have caused.

**Comment by jody** [comment]
> I was unable to cleanly roll back my unrelated changes, so I just created Pull Request #162, which should have only the necessary changes for the SpotBugs implementation. My apologies for any confusion this may have caused.

Based on this comment I am closing the PR.

**Pull request closed without merging**
