### PR TITLE
Added JaCoCo plugin to build file

### PR DESCRIPTION
**Pull request by henrykgray**
Addresses user story #107

### CODE REVIEW

**Comment by henrykgray** [comment]
> What is the verification that this works as intended?
> Please include test results as validation.
Hi Jody,
For verification would you like the JaCoCo report that was generated for the Library method to be included in the pull request?
-Henry

**Comment by jody** [comment]
> Hi Jody,
> For verification would you like the JaCoCo report that was generated for the Library method to be included in the pull request?
> -Henry

That would be OK.  The primary concern is simply how the reviewer would know whether or not the pull request behaves as intended.  It could also be an example of its usage, such as the commands that would be issued, where the results would be found, etc.

This also seems to suggest that associated documentation for maintainers would be a valuable component to this PR.

**Comment by jody** [comment]
The maintainer's instructions are appreciated!
* Please have someone else (in your team or another) proofread the document (for both clarity and correctness).

I see that we had different interpretations of the JaCoCo report being "included in the pull request".  My intent was not to have the image added to the repository, but for it to be referenced directly within this pull request itself, like this:
jaCoCoReportVerification

That's now taken care of (by virtue of appearing in this conversation).
* Please modify the pull request so that the PNG file is not added to the repository.

Thanks!

**Comment by henrykgray** [comment]
PNG file has been removed and @MaTTerCuBe has helped with proofreading the document.

**Pull request merged**
