### PR TITLE
Add skeletal ToolEncapsulation class to QualityToolsForBlueJ main Repo

### PR DESCRIPTION
**Pull request by JustinSingleton303**
Here is the start of the ToolEncapsulation class

### CODE REVIEW

**Comment by jody** [comment]
Is this a duplicate of PR #103?

**Comment by JustinSingleton303** [comment]
okay I will fix those tags and resubmit

**Comment by jody** [comment]
Duplicate of #103

**Comment by Derplicity** [comment]
Can be closed.

**Comment by jody** [comment]
> Can be closed.

OK.  Will close this; leaving PR #103

**Pull request closed without merging**
